../build/make.exe: main.cpp target.h target.cpp reader.h reader.cpp makefile.h makefile.cpp utils.h utils.cpp
	g++ -o ../build/make.exe main.cpp target.h target.cpp reader.h reader.cpp makefile.h makefile.cpp utils.h utils.cpp

linux: #../build/make.exe
	cos tam
